WITH current_from_snapshot AS (
    SELECT *
    FROM {{ ref('SNSH_ABC_BANK_POSITION') }}
    WHERE DBT_VALID_TO IS NULL 
)
SELECT 
    *,
    (POSITION_VALUE - COST_BASE) AS UNREALIZED_PROFIT,
    ROUND((UNREALIZED_PROFIT / COST_BASE), 5)*100 AS UNREALIZED_PROFIT_PCT
FROM current_from_snapshot